# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 03020693e7b2d32b7fe3943d032e5342ba7cd441bd5fe8badac1ff82480b2642fc6f05799ad2fc09db054e5550267e999680a81fece333b45da003e97a1435a9

test:
  secret_key_base: e29619546ed63078f02b02f52281f9479bf94252a4d97d365150241ca61b275c53256238eb858ac7e4c069b9039810469e967a91dfbd30a72d1a8261362a3553

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
